Add-Type -AssemblyName System.Drawing

$ProjectRoot = Split-Path -Parent $MyInvocation.MyCommand.Path
$OutDir = Join-Path $ProjectRoot "main"

$FontPath = "C:\Windows\Fonts\simhei.ttf"

# Extra glyph list generated by AirTouch UI Chinese scan.
# The latest p4_cn_glyphs_needed_v2n1_*.txt will be loaded automatically.
$GlyphDir = Join-Path $ProjectRoot "logs"
$GlyphFile = Get-ChildItem $GlyphDir -Filter "p4_cn_glyphs_needed_v2n1_*.txt" -ErrorAction SilentlyContinue |
    Sort-Object LastWriteTime -Descending |
    Select-Object -First 1

if (-not (Test-Path $FontPath)) {
    Write-Host "Font not found: $FontPath"
    exit 1
}

# ASCII-safe Unicode list for all Chinese characters and symbols used by UI.
# Do not put direct Chinese text in this file.
$ExtraCodes = @(                 0x4F1A, 0x5220, 0x5931, 0x8BD5, 0x8D25, 0x90FD, 0x9ED8,
0x4E0A, 0x4ECD, 0x4FEE, 0x518D, 0x521D, 0x548C, 0x590D, 0x5E76, 0x5F55, 0x6062, 0x6216, 0x6301, 0x652F, 0x6539, 0x65AD, 0x6ED1, 0x7136, 0x7406, 0x7535, 0x7559, 0x786E, 0x7BA1, 0x8BA4, 0x9700,
0x636E, 0x6B21, 0x97F3, 0x91CF, 0x7D2F, 0x8BA1, 0x672C,
0x907F, 0x8272, 0x70B8, 0x5F39,
0x51FA,  0x7565,  0x7B56,  0x5E94,  0x53CD,  0x4F5C,  0x82B1,  0x6708,  0x661F,  0x540C,  0x76F8,  0x627E,  0x914D,  0x6848,  0x56FE,  0x529B,  0x6CE8,  0x4E13,  0x724C,  0x7FFB,  0x5FC6,  0x8BB0,  0x8F7D,  0x5728,  0x96BE,  0x56F0,  0x666E,  0x5355,  0x7B80,  0x4EBA, 0x673A, 0x5BF9, 0x6218, 0x6A21, 0x5F0F, 0x73A9, 0x5BB6, 0x6267, 0x9ED1, 0x767D, 0x68CB, 0x843D, 0x5B50, 0x540E, 0x81EA, 0x52A8,  0x4E0B, 0x4E49, 0x4F7F, 0x53D6, 0x5B9A, 0x5C0F, 0x6B65, 0x6D88, 0x7528, 0x79D2,  0x4F11, 0x4F4D, 0x4FDD, 0x5165, 0x5230, 0x5566, 0x56DB, 0x5B57, 0x5B58, 0x5BB6, 0x5BC6, 0x5DF2, 0x606F, 0x65B0, 0x65F6, 0x66F4, 0x6E05, 0x7801, 0x8BEF, 0x8BF7, 0x8F93, 0x89E3, 0x9501, 0x9519, 0x9664,  0x4E0E, 0x4F59, 0x5173, 0x5230, 0x5269, 0x542F, 0x5BB6, 0x5BC6, 0x5DF2, 0x62E9, 0x73A9, 0x7801, 0x89E3, 0x9009, 0x949F, 0x9501, 0x957F, 0x95ED, 0x9664,  0x5212, 0x522B, 0x67E5, 0x7B49, 0x89C4, 0x8BC6, 0x8BE6, 0x7EC6, 0x5217, 0x8868, 0x9875, 
    0x00B7, 0x00D7, 0x3001, 0x3002, 0x4E00, 0x4E2D, 0x4E3A, 0x4E92, 0x4E94, 0x4EA4,
    0x4EBA, 0x4F18, 0x4FE1, 0x50CF, 0x513F, 0x5148, 0x5165, 0x51FB, 0x5206, 0x5207,
    0x5236, 0x524D, 0x529F, 0x52A0, 0x52A8, 0x5316, 0x5361, 0x53C9, 0x53CB, 0x53CC,
    0x53D1, 0x53EF, 0x53F0, 0x540D, 0x540E, 0x5473, 0x56DE, 0x589E, 0x5907, 0x591A,
    0x5934, 0x597D, 0x59CB, 0x5B50, 0x5BF9, 0x5C06, 0x5C0F, 0x5C16, 0x5C40, 0x5C4F,
    0x5C55, 0x5E38, 0x5E73, 0x5F00, 0x5F0F, 0x5F53, 0x5F97, 0x5FC3, 0x6001, 0x606F,
    0x620F, 0x6210, 0x6218, 0x624B, 0x6269, 0x6307, 0x63A5, 0x63A7, 0x6444, 0x6478,
    0x6548, 0x6570, 0x65B0, 0x65B9, 0x65F6, 0x663E, 0x66F4, 0x672A, 0x673A, 0x675F,
    0x677F, 0x679C, 0x67B6, 0x6846, 0x68CB, 0x6A21, 0x6B63, 0x6C34, 0x6D41, 0x6E38,
    0x6F14, 0x70B9, 0x72B6, 0x754C, 0x767D, 0x7684, 0x76D8, 0x76EE, 0x770B, 0x77E5,
    0x793A, 0x79F0, 0x7A7A, 0x7AE5, 0x7ED3, 0x7EED, 0x7F6E, 0x80DC, 0x80FD, 0x81EA,
    0x83B7, 0x843D, 0x884C, 0x89C2, 0x89E6, 0x8BBE, 0x8DA3, 0x8F6E, 0x8FD0, 0x8FD4,
    0x8FDB, 0x8FDE, 0x901A, 0x91CD, 0x95F4, 0x9762, 0x9879, 0x9ED1, 0xFF0C, 0xFF1A,
    0xFF1B,
    0x65E0, # 无
    0x5C3D, # 尽
    0x6F0F, # 漏
    0x6263, # 扣
    0x751F, # 生
    0x547D, # 命
    0x7EA7, # 级
    0x5F97, # 得
    0x6700, # 最
    0x9AD8, # 高
    0x6389  # 掉
)

function Get-UniqueCodes {
    $set = New-Object System.Collections.Generic.HashSet[int]

    for ($i = 32; $i -le 126; $i++) {
        [void]$set.Add($i)
    }

    foreach ($code in $ExtraCodes) {
        [void]$set.Add([int]$code)
    }

    if ($null -ne $GlyphFile -and (Test-Path $GlyphFile.FullName)) {
        Write-Host "Load extra glyphs from $($GlyphFile.FullName)"
        $glyphText = Get-Content $GlyphFile.FullName -Raw -Encoding UTF8
        foreach ($ch in $glyphText.ToCharArray()) {
            $code = [int][char]$ch
            if ($code -ge 32) {
                [void]$set.Add($code)
            }
        }
    } else {
        Write-Host "No extra glyph file found, use built-in ExtraCodes only."
    }

    $arr = New-Object System.Collections.Generic.List[int]
    foreach ($v in $set) {
        $arr.Add($v)
    }

    $arr.Sort()
    return $arr
}

function ByteArrayToC {
    param(
        [byte[]]$data,
        [int]$indent = 4
    )

    $lines = New-Object System.Collections.Generic.List[string]
    $line = " " * $indent
    $count = 0

    foreach ($b in $data) {
        $item = ("0x{0:x2}, " -f $b)
        $line += $item
        $count++

        if ($count -ge 12) {
            $lines.Add($line)
            $line = " " * $indent
            $count = 0
        }
    }

    if ($line.Trim().Length -gt 0) {
        $lines.Add($line)
    }

    return ($lines -join "`r`n")
}

function UInt16ArrayToC {
    param(
        [int[]]$data,
        [int]$indent = 4
    )

    $lines = New-Object System.Collections.Generic.List[string]
    $line = " " * $indent
    $count = 0

    foreach ($v in $data) {
        $item = ("0x{0:x}, " -f $v)
        $line += $item
        $count++

        if ($count -ge 10) {
            $lines.Add($line)
            $line = " " * $indent
            $count = 0
        }
    }

    if ($line.Trim().Length -gt 0) {
        $lines.Add($line)
    }

    return ($lines -join "`r`n")
}

function Generate-Font {
    param(
        [int]$Size,
        [string]$OutFile,
        [string]$VarName
    )

    $chars = Get-UniqueCodes

    $privateFonts = New-Object System.Drawing.Text.PrivateFontCollection
    $privateFonts.AddFontFile($FontPath)
    $family = $privateFonts.Families[0]

    $font = New-Object System.Drawing.Font(
        $family,
        [float]$Size,
        [System.Drawing.FontStyle]::Regular,
        [System.Drawing.GraphicsUnit]::Pixel
    )

    $bmpBytes = New-Object System.Collections.Generic.List[byte]
    $glyphDsc = New-Object System.Collections.Generic.List[string]

    $glyphDsc.Add("    {.bitmap_index = 0, .adv_w = 0, .box_w = 0, .box_h = 0, .ofs_x = 0, .ofs_y = 0}, /* id = 0 reserved */")

    $bitmapIndex = 0
    $glyphId = 1

    foreach ($code in $chars) {
        $ch = [string][char]$code

        $bmp = New-Object System.Drawing.Bitmap($Size, $Size, [System.Drawing.Imaging.PixelFormat]::Format32bppArgb)
        $g = [System.Drawing.Graphics]::FromImage($bmp)

        $g.Clear([System.Drawing.Color]::Black)
        $g.TextRenderingHint = [System.Drawing.Text.TextRenderingHint]::AntiAliasGridFit
        $g.SmoothingMode = [System.Drawing.Drawing2D.SmoothingMode]::HighQuality
        $g.InterpolationMode = [System.Drawing.Drawing2D.InterpolationMode]::HighQualityBicubic
        $g.PixelOffsetMode = [System.Drawing.Drawing2D.PixelOffsetMode]::HighQuality

        $brush = New-Object System.Drawing.SolidBrush([System.Drawing.Color]::White)
        $format = [System.Drawing.StringFormat]::GenericTypographic
        $format.FormatFlags = $format.FormatFlags -bor [System.Drawing.StringFormatFlags]::NoClip

        $g.DrawString($ch, $font, $brush, 0, 0, $format)

        $rowBytes = New-Object System.Collections.Generic.List[byte]

        for ($y = 0; $y -lt $Size; $y++) {
            for ($x = 0; $x -lt $Size; $x += 2) {
                $p1 = $bmp.GetPixel($x, $y)
                $v1 = [int][Math]::Round($p1.R / 17.0)
                if ($v1 -lt 0) { $v1 = 0 }
                if ($v1 -gt 15) { $v1 = 15 }

                $v2 = 0
                if (($x + 1) -lt $Size) {
                    $p2 = $bmp.GetPixel($x + 1, $y)
                    $v2 = [int][Math]::Round($p2.R / 17.0)
                    if ($v2 -lt 0) { $v2 = 0 }
                    if ($v2 -gt 15) { $v2 = 15 }
                }

                $packed = (($v1 -shl 4) -bor $v2)
                [void]$rowBytes.Add([byte]$packed)
            }
        }

        foreach ($bb in $rowBytes) {
            [void]$bmpBytes.Add($bb)
        }

        $adv = $Size * 16
        $glyphDsc.Add("    {.bitmap_index = $bitmapIndex, .adv_w = $adv, .box_w = $Size, .box_h = $Size, .ofs_x = 0, .ofs_y = 0}, /* id = $glyphId U+$('{0:X4}' -f $code) */")

        $bitmapIndex += $rowBytes.Count

        $brush.Dispose()
        $g.Dispose()
        $bmp.Dispose()

        $glyphId++
    }

    $minCode = $chars[0]
    $offsets = New-Object System.Collections.Generic.List[int]
    foreach ($code in $chars) {
        $offsets.Add($code - $minCode)
    }

    $bitmapC = ByteArrayToC ([byte[]]$bmpBytes.ToArray())
    $offsetC = UInt16ArrayToC ([int[]]$offsets.ToArray())
    $glyphC = $glyphDsc -join "`r`n"

    $glyphCount = $chars.Count
    $rangeLen = $chars[$chars.Count - 1] - $minCode + 1
    $lineHeight = $Size
    $baseLine = 0

    $c = @"
#include "lvgl.h"

#ifndef LV_ATTRIBUTE_LARGE_CONST
#define LV_ATTRIBUTE_LARGE_CONST
#endif

static LV_ATTRIBUTE_LARGE_CONST const uint8_t ${VarName}_glyph_bitmap[] = {
$bitmapC
};

static const lv_font_fmt_txt_glyph_dsc_t ${VarName}_glyph_dsc[] = {
$glyphC
};

static const uint16_t ${VarName}_unicode_list_0[] = {
$offsetC
};

static const lv_font_fmt_txt_cmap_t ${VarName}_cmaps[] = {
    {
        .range_start = $minCode,
        .range_length = $rangeLen,
        .glyph_id_start = 1,
        .unicode_list = ${VarName}_unicode_list_0,
        .glyph_id_ofs_list = NULL,
        .list_length = $glyphCount,
        .type = LV_FONT_FMT_TXT_CMAP_SPARSE_TINY
    }
};

#if LVGL_VERSION_MAJOR == 8
static lv_font_fmt_txt_glyph_cache_t ${VarName}_cache;
#endif

#if LVGL_VERSION_MAJOR >= 8
static const lv_font_fmt_txt_dsc_t ${VarName}_font_dsc = {
#else
static lv_font_fmt_txt_dsc_t ${VarName}_font_dsc = {
#endif
    .glyph_bitmap = ${VarName}_glyph_bitmap,
    .glyph_dsc = ${VarName}_glyph_dsc,
    .cmaps = ${VarName}_cmaps,
    .kern_dsc = NULL,
    .kern_scale = 0,
    .cmap_num = 1,
    .bpp = 4,
    .kern_classes = 0,
    .bitmap_format = 0,
#if LVGL_VERSION_MAJOR == 8
    .cache = &${VarName}_cache
#endif
};

#if LVGL_VERSION_MAJOR >= 8
const lv_font_t $VarName = {
#else
lv_font_t $VarName = {
#endif
    .get_glyph_dsc = lv_font_get_glyph_dsc_fmt_txt,
    .get_glyph_bitmap = lv_font_get_bitmap_fmt_txt,
    .line_height = $lineHeight,
    .base_line = $baseLine,
#if !(LVGL_VERSION_MAJOR == 6 && LVGL_VERSION_MINOR == 0)
    .subpx = LV_FONT_SUBPX_NONE,
#endif
#if LV_VERSION_CHECK(7, 4, 0) || LVGL_VERSION_MAJOR >= 8
    .underline_position = -1,
    .underline_thickness = 1,
#endif
    .dsc = &${VarName}_font_dsc,
#if LV_VERSION_CHECK(8, 2, 0) || LVGL_VERSION_MAJOR >= 9
    .fallback = NULL,
#endif
    .user_data = NULL,
};
"@

    Set-Content -Path $OutFile -Value $c -Encoding UTF8

    Write-Host "Generated $OutFile chars=$glyphCount size=$Size"
}

Generate-Font -Size 20 -OutFile (Join-Path $OutDir "ui_font_cn_20.c") -VarName "ui_font_cn_20"
Generate-Font -Size 26 -OutFile (Join-Path $OutDir "ui_font_cn_26.c") -VarName "ui_font_cn_26"
Generate-Font -Size 32 -OutFile (Join-Path $OutDir "ui_font_cn_32.c") -VarName "ui_font_cn_32"

Write-Host "Done."


















